name: Test

on:
  # run when action is manually triggered
  workflow_dispatch:
  # run on pull requests
  pull_request:

jobs:
  test-run:
    name: Run tests

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Node v14
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "npm"

      - name: Install npm dependencies
        run: npm ci

      - name: Install Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Load pip cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: py-${{ hashFiles('converter/textbook-converter/requirements.txt') }}

      - name: Install Python dependencies
        run: pip install -r converter/textbook-converter/requirements.txt

      - name: Notebook tests
        run: npm run test:nb

      - name: Build
        run: npm run build

      - name: Cypress tests
        uses: cypress-io/github-action@v2
        with:
          start: npm start
          wait-on: 'http://localhost:8080/health'
